language: ruby
services:
  - postgresql
rvm:
  - 2.6.3
cache:
  directories:
  - /home/travis/.rvm/
  bundler: true
  yarn: true
before_install:
  - gem install bundler -v 2.0.2
  - cp config/database.yml.travis config/database.yml
  - bundle install
  - psql -c 'create database laba42_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
script:
  - "bundle exec rspec"
  - "bundle exec rubocop"
  - "bundle exec reek"
deploy:
  provider: heroku
  api_key:
    secure: "IqoahF9tIakLG+EqHCnkBXIFb5/QtqclSgyKbp+lFFYi+aJ5MvUaXPepYqddQCj2rjmAeblRbd+qCRdWPqiWsY/kOrLnQ78Q9dYJJnOTtZgC9xxrE3Cp6GBnJFJOcBxg02oWM+tXb4BtiwQJ64qf7MWktQh79hv87sltBdDTDuI50e1rQ+JDehqfXEOqu/HKSu3r+HBoNf14UkHrky4YQbzuUknPdOfyZik8vwvvUzRzcmkKsqVthoFwV5CjSgypkeAUen+7vrwLFXjFwCBNY5OQjNI4MkvG0VF/6qZf9nyEF7sCkDcizSNVF9b0mwWNuRKonT5G/XQw+UYUdKn7aiG8xYbnBEgYL7Z2Yq4yrWg9YAFO2ZZeBnJkGyUPBu0Q/zTo7aNtIaewHagGQ5Dhwc4JvBV/AY7XqgAMss7uTtEwkV3mLGfGFkhjJg4WvgFsfz3dtnfcG+z0rxeZ67xJbji0FVaBrgjNZMbZGYU9yQ/E9RMZqOxX+OyXQnISkR0EapzBL/JuUzHd5K4nLSJ7ywtZ1LcbHZoMwwzMR1E6icxiIhLE6id01M3LwT1eOMF+lvzs4r5X3AfijQyOTRigmUozOVbZjktiQDe+O6cbp+7YulPbszOi1joSYTpvCkLQFo0oC+9IOllF/+TsY8vPHGg+w/1CJk9PjNs8qx7GOUw="
  app: mysterious-retreat-89613
  on:
    repo: Almix047/laba42
