language: ruby
services:
  - postgresql
rvm:
  - 2.6.3
cache:
  directories:
  - /home/travis/.rvm/
  bundler: true
  yarn: true
before_install:
  - gem install bundler -v 2.0.2
  - cp config/database.yml.travis config/database.yml
  - bundle install
  - psql -c 'create database laba42_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
script:
  - "bundle exec rspec"
  - "bundle exec rubocop"
  - "bundle exec reek"
deploy:
  provider: heroku
  api_key:
    secure: "yHC+yXDjgdaZZVZ+JnbBkxZfIJP1Rfv6Oufly6Hu3z2XYHRsUvZXfQOo1Y+0grin2vqaymUVjaX7K+hAy0pUMjI+3Dp+VyXl8IP73wrirTrsHDtvHhIZ3B9uAXK85kVD/IWWXxS1g5VKvkG5nMaPuhddRK+yhi3Yy5M05i7i3AXL3GT7OqZKlkDoS7sH0RP9p7bIQKM1ETwBI8vNeXCOk9WsPw7Gy35q92MSroygccN1pQNQHSslrYO7eSnQiUGI9NX9MOOyMwASosoyk1xG3NZoPPwsFkiiIqZ4WMv+I1RhFxbialGyNvZQovMfdu7eracTrl9GWxmpq1ZqLVQ96L5ttL7AtDVSuqj3CeZiQYIf7nJt2sIMYaQ8NgRoDxXtJXVo2Ldacd0bXX4CFLKJdkNFpg3Pie5akX85x0aS/UGcf8Q+7FAq8op3gZwy1ntS0hFRhpAK1k2UpOp61V+FOJLM/ImRJcCvUpNkEEwtNlkRFuW2/yejvBwZ7Paxfvnzl8bmLFOYOs5QviW5nwT/F0bAXnLSL/QKQ3muQ1iT24Ll2MEKMqfFEUb2OugBybarFg2RaAWKy2jMBdJFYZdDUV84SVlgbisgNe0EA2f79KyWmXzbiR9kUJgtxIdL0qsbYvOI415cxTrr0uvZXVHEnvKZHwSE3vgJHSJw1m77a3Q="
  app: mysterious-retreat-89613
  on:
    repo: Almix047/laba42
