language: ruby
services:
  - postgresql
rvm:
  - 2.6.3
cache:
  directories:
  - /home/travis/.rvm/
  bundler: true
  yarn: true
before_install:
  - gem install bundler -v 2.0.2
  - cp config/database.yml.travis config/database.yml
  - bundle install
  - psql -c 'create database laba42_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
script:
  - "bundle exec rspec"
  - "bundle exec rubocop"
  - "bundle exec reek"
deploy:
  provider: heroku
  api_key:
    secure: "NUOH1UXevGafCjnr0nQzZgbbV395ewEBYZ0iw8vxPxLa5g8kNbv34e3wWbVyyJBP6vvDh306OIQ1iA+kopYth/tRtfA4r+V5zo57a6lCDzTcKjyb84crLthTeN0tj+zJIzzcc2Gk5ecdJXsPIBOdORzuSD5M4DwFMhpeMLMxOfdaCh8cSrrJAkuhOqYVjZ+WDcCWP4ZkR4FUrE6qTwVYjeIUMjF7SQhnUhdB8kOVpF4nijhayZK8l47LR/QQ0UTlojQqKgkqCUtP+ESRJE1JPuHHM6E4eFUZS+6/+Wfw6J/sDk9pdDPaNAYRpdBfiVHLpwcmzpion8+WM1YZerr7ByflFnRbat0aJz8JpuPHXhXKOuVegV05/JAetTG3z7QkGb5XlIg0CP6dRAt5e1wsEcf30XBDQGFdbgtsCw2UgFJKhEyNa0h5zPJn7LI/ojmYnuz49h/JyqydT0QdB6aJqJX3QWqQqLJ8JMdB8KMJFLkODaxMUciB2rReUHDGlZqvCFp+ojZhzoBCLTAkxyXFmUdp43bNycsspMCrBNu0393fMezNNRnYAHhyhkSgDxN6bNyfTY0FFDBPqc4uWwxkMDGVLtk72fWYzXAhnIClkAtSBv6eupLYOObCJsS8ArJrcNpj948gVGymDKDCaugtzInoU4kZl36t8LIZdKNf9MU="
  app: mysterious-retreat-89613
  on:
    repo: Almix047/laba42
